# Mandatory
port: 5000

# Mandatory.
cache:
  host: "localhost"
  port: 6379
  ttl: "PT10M"
  # Optional. Default is 0.
  dbNumber: 5

# Optional.
responseCache:
  enabled: true
  mongoURL: "mongodb://root:password@localhost:27017/protocolServer?authSource=admin"
  ttl: "PT10M"

# Mandatory.
# Priority order will be
# 1. Synchronous
# 2. webhook
# 3. pubSub
client:
  synchronous: true

  webhook:
    url: "https://beckn.free.beeceptor.com/clientURL"
  
  pubSub: 
    amqpUrl: "amqp://guest:guest@localhost:5672"
    client-inbox-queue: "bap-protocol-server"
    client-outbox-queue: "bap-protocol-client"

# TODO: yet to decide Client Auth for requests.

# Mandatory.
app:
  # Mandatory.
  mode: bap

  # Mandatory.
  actions:
    requests:
      - search
      - init
    
    responses:
      - on_search
      - on_init
  
  # Mandatory.
  privateKey: "your private key"
  publicKey: "your public key"

  # Mandatory.
  subscriberId: "dev.bap.protocol-server.com"
  subscriberUri: "https://ayush.free.beeceptor.com/"
  
  # Mandatory.
  registryUrl: https://registry.becknprotocol.io/subscribers
  auth: true
  uniqueKey: "dev.bap.protocol-server.key"
  
  # Mandatory.
  city: "std:080"
  country: "IND"

  # Mandatory.
  ttl: "PT10M"

  # Mandatory.
  httpTimeout: 3000
  httpRetryCount: 2